// 'detail.*' UI strings. Populated by the i18n extraction; keys are flat and
// must carry the 'detail.' prefix (enforced by tests-unit/i18n.test.ts).
export const detailStrings = {
  'detail.click_to_copy': 'Click to copy',
  'detail.route_source_acars': 'ACARS',
  'detail.route_source_acars_tooltip': 'Destination from ACARS datalink',
  'detail.eta': 'ETA {time}',
  'detail.phase_at_gate': 'At gate',
  'detail.phase_taxi_out': 'Taxiing out',
  'detail.phase_airborne': 'Airborne',
  'detail.phase_taxi_in': 'Taxiing in',
  'detail.phase_arrival_gate': 'At arrival gate',
  'detail.operator': 'Operator',
  'detail.class': 'Class',
  'detail.chip_military': 'Military',
  'detail.chip_special_interest': 'Special interest',
  'detail.chip_pia': 'PIA',
  'detail.chip_ladd': 'LADD',
  'detail.on_ground': 'GND',
  'detail.vertical_level': 'level',
  'detail.seconds_ago': '{n}s ago',
  'detail.minutes_ago': '{n}m ago',
  'detail.hours_ago': '{n}h ago',
  'detail.selected_altitude': 'Sel. Alt',
  'detail.fms_altitude': 'FMS Alt',
  'detail.selected_heading': 'Sel. Hdg',
  'detail.qnh': 'QNH',
  'detail.autopilot_modes': 'Modes',
  'detail.acars_err': 'err {n}',
  'detail.acars_out': 'OUT {time}',
  'detail.acars_off': 'OFF {time}',
  'detail.acars_on': 'ON {time}',
  'detail.acars_in': 'IN {time}',
  'detail.acars_pos': 'pos {coords}',
  'detail.acars_no_text': '(no text)',
  'detail.category_light': 'Light (< 7t)',
  'detail.category_small': 'Small (< 34t)',
  'detail.category_large': 'Large (< 136t)',
  'detail.category_high_vortex': 'High-vortex large',
  'detail.category_heavy': 'Heavy (> 136t)',
  'detail.category_high_performance': 'High performance',
  'detail.category_rotorcraft': 'Rotorcraft',
  'detail.category_glider': 'Glider',
  'detail.category_lighter_than_air': 'Lighter-than-air',
  'detail.category_parachutist': 'Parachutist',
  'detail.category_ultralight': 'Ultralight',
  'detail.category_uav': 'UAV',
  'detail.category_spacecraft': 'Spacecraft',
  'detail.category_surface_unknown': 'Surface — unknown',
  'detail.category_surface_emergency': 'Surface — emergency',
  'detail.category_surface_service': 'Surface — service',
  'detail.category_surface_obstacle': 'Surface — fixed obstacle',
  'detail.compass_n': 'N',
  'detail.compass_ne': 'NE',
  'detail.compass_e': 'E',
  'detail.compass_se': 'SE',
  'detail.compass_s': 'S',
  'detail.compass_sw': 'SW',
  'detail.compass_w': 'W',
  'detail.compass_nw': 'NW',
} as const;
