// 'settings.*' UI strings. Populated by the i18n extraction; keys are flat and
// must carry the 'settings.' prefix (enforced by tests-unit/i18n.test.ts).
export const settingsStrings = {
  // Panel chrome
  'settings.title': 'Settings',
  'settings.close': 'Close settings',

  // Theme section
  'settings.section_theme': 'Theme',
  'settings.color_theme': 'Color theme',
  'settings.color_theme_desc': 'Palette for panels, accents, and the scene background. Auto follows your system light/dark preference.',
  'settings.language': 'Language',
  'settings.language_desc': "UI language. Auto follows your browser's locale. Changing this reloads the page.",
  'settings.language_auto': 'Auto',

  // Display section
  'settings.section_display': 'Display',
  'settings.ground_sprites': 'Ground aircraft icons',
  'settings.ground_sprites_desc': 'Show the tar1090 silhouette under each aircraft.',
  'settings.altitude_lines': 'Altitude lines',
  'settings.altitude_lines_desc': 'Vertical line dropping each aircraft to its ground position.',
  'settings.aircraft_labels': 'Aircraft labels',
  'settings.aircraft_labels_desc': 'Callsign / registration / hex above each aircraft.',
  'settings.acars_messages': 'ACARS messages',
  'settings.acars_messages_desc': 'Show ACARS datalink messages and the receiver status chip.',
  'settings.label_density': 'Label density',
  'settings.label_density_desc': 'Higher values hide farther-away labels when zoomed in. 0 keeps every label visible.',
  'settings.label_density_all': 'all',
  'settings.range_rings': 'Range rings',
  'settings.range_rings_desc': 'Concentric distance rings every 50 NM.',
  'settings.basemap': 'Basemap',
  'settings.basemap_desc': 'Map tile provider drawn beneath the scene.',
  'settings.basemap_carto_dark': 'Carto Dark',
  'settings.basemap_carto_voyager': 'Carto Voyager (light)',
  'settings.basemap_osm': 'OpenStreetMap',
  'settings.basemap_topo': 'OpenTopoMap',
  'settings.basemap_hillshade': 'ESRI Hillshade',
  'settings.basemap_satellite': 'ESRI Satellite',
  'settings.basemap_sectional': 'FAA Sectional (US)',
  'settings.basemap_sectional_hybrid': 'FAA Sectional + Roads (US)',
  'settings.basemap_helicopter': 'FAA Helicopter (US)',
  'settings.basemap_ifr_low': 'FAA IFR Low (US)',
  'settings.basemap_ifr_high': 'FAA IFR High (US)',

  // Stereo / VR section
  'settings.section_stereo_vr': 'Stereo / VR',
  'settings.enter_vr': 'Enter VR',
  'settings.enter_vr_desc': 'Open an immersive WebXR session in a connected headset (Meta Quest, Vision Pro, etc.).',
  'settings.exit_vr': 'Exit VR',
  'settings.exit_vr_desc': 'End the active immersive session.',
  'settings.exit_ar_first': 'Exit the AR session first.',
  'settings.vr_unavailable': 'VR unavailable',
  'settings.webxr_unavailable': 'WebXR is not available in this browser.',
  'settings.enter_ar': 'Enter AR',
  'settings.enter_ar_desc': 'Passthrough mode — aircraft floating in your room. Quest 3, Vision Pro.',
  'settings.exit_ar': 'Exit AR',
  'settings.exit_ar_desc': 'End the active passthrough session.',
  'settings.exit_vr_first': 'Exit the VR session first.',
  'settings.ar_unavailable': 'AR unavailable',
  'settings.ar_unsupported': 'This device does not support immersive-ar passthrough.',
  'settings.vr_quality': 'VR render quality',
  'settings.vr_quality_desc': 'Supersampling for immersive VR. Higher keeps distant aircraft sharp at a GPU cost. Takes effect the next time you enter VR.',
  'settings.vr_quality_low': 'Low (faster)',
  'settings.vr_quality_balanced': 'Balanced',
  'settings.vr_quality_high': 'High',
  'settings.vr_quality_ultra': 'Ultra (sharpest)',
  'settings.stereo': 'Side-by-side stereo',
  'settings.stereo_desc': 'Split the view into left/right eye halves for Google Cardboard or a phone VR headset. Ignored while an immersive WebXR session is active.',
  'settings.stereo_strength': 'Stereo strength',
  'settings.stereo_strength_desc': 'Eye separation when stereo is on. Higher gives deeper 3D but more eye strain.',

  // Units section
  'settings.section_units': 'Units',
  'settings.altitude_unit': 'Altitude',
  'settings.unit_feet': 'Feet (ft)',
  'settings.unit_meters': 'Meters (m)',
  'settings.speed_unit': 'Speed',
  'settings.unit_knots': 'Knots (kt)',
  'settings.unit_mph': 'Miles/hour (mph)',
  'settings.unit_kmh': 'Kilometers/hour (km/h)',
  'settings.distance_unit': 'Distance',
  'settings.unit_nm': 'Nautical miles (NM)',
  'settings.unit_km': 'Kilometers (km)',

  // Range-row reset button
  'settings.reset_to_default': 'Reset to default ({value})',
  'settings.reset_row_to_default': 'Reset {label} to default',
  'settings.altitude_curve': 'Altitude scale',
  'settings.altitude_curve_desc':
    'How altitude maps to height in the 3D view. Low-altitude detail spreads out ' +
    'pattern traffic; high-altitude detail spreads out the flight levels. ' +
    'Changing this reloads the page.',
  'settings.altitude_curve_linear': 'Balanced (linear)',
  'settings.altitude_curve_spread_low': 'Low-altitude detail',
  'settings.altitude_curve_spread_high': 'High-altitude detail',
} as const;
