// Spanish draft mirroring en/detail.ts — pending native-speaker review.
export const detailStrings = {
  'detail.click_to_copy': 'Clic para copiar',
  'detail.route_source_acars': 'ACARS',
  'detail.route_source_acars_tooltip': 'Destino según enlace de datos ACARS',
  'detail.eta': 'ETA {time}',
  'detail.phase_at_gate': 'En puerta',
  'detail.phase_taxi_out': 'Rodaje de salida',
  'detail.phase_airborne': 'En vuelo',
  'detail.phase_taxi_in': 'Rodaje de llegada',
  'detail.phase_arrival_gate': 'En puerta de llegada',
  'detail.operator': 'Operador',
  'detail.class': 'Clase',
  'detail.chip_military': 'Militar',
  'detail.chip_special_interest': 'Interés especial',
  'detail.chip_pia': 'PIA',
  'detail.chip_ladd': 'LADD',
  'detail.on_ground': 'GND',
  'detail.agl': '{agl} AGL',
  'detail.vertical_level': 'nivelado',
  'detail.seconds_ago': 'hace {n}s',
  'detail.minutes_ago': 'hace {n}m',
  'detail.hours_ago': 'hace {n}h',
  'detail.selected_altitude': 'Alt. sel.',
  'detail.fms_altitude': 'Alt. FMS',
  'detail.selected_heading': 'Rumbo sel.',
  'detail.qnh': 'QNH',
  'detail.autopilot_modes': 'Modos',
  'detail.acars_err': 'err {n}',
  'detail.acars_out': 'OUT {time}',
  'detail.acars_off': 'OFF {time}',
  'detail.acars_on': 'ON {time}',
  'detail.acars_in': 'IN {time}',
  'detail.acars_pos': 'pos {coords}',
  'detail.acars_no_text': '(sin texto)',
  'detail.category_light': 'Ligera (< 7t)',
  'detail.category_small': 'Pequeña (< 34t)',
  'detail.category_large': 'Grande (< 136t)',
  'detail.category_high_vortex': 'Grande de alta turbulencia',
  'detail.category_heavy': 'Pesada (> 136t)',
  'detail.category_high_performance': 'Altas prestaciones',
  'detail.category_rotorcraft': 'Giroavión',
  'detail.category_glider': 'Planeador',
  'detail.category_lighter_than_air': 'Más ligero que el aire',
  'detail.category_parachutist': 'Paracaidista',
  'detail.category_ultralight': 'Ultraligero',
  'detail.category_uav': 'UAV',
  'detail.category_spacecraft': 'Nave espacial',
  'detail.category_surface_unknown': 'Superficie — desconocido',
  'detail.category_surface_emergency': 'Superficie — emergencia',
  'detail.category_surface_service': 'Superficie — servicio',
  'detail.category_surface_obstacle': 'Superficie — obstáculo fijo',
  'detail.compass_n': 'N',
  'detail.compass_ne': 'NE',
  'detail.compass_e': 'E',
  'detail.compass_se': 'SE',
  'detail.compass_s': 'S',
  'detail.compass_sw': 'SO',
  'detail.compass_w': 'O',
  'detail.compass_nw': 'NO',
} as const;
