// Spanish draft mirroring en/main.ts — pending native-speaker review.
export const mainStrings = {
  'main.status_live': 'en vivo',
  'main.status_stale': 'desactualizado',
  'main.status_down': 'caído',
  'main.status_connecting': 'conectando',
  'main.status_historical': 'histórico',
  'main.connecting_feed': 'Conectando',
  'main.feed_connecting': 'conectando…',
  'main.feed_status_down': '{feed} · caído',
  'main.feed_status_stale': '{feed} · desactualizado',
  'main.feed_status_stale_age': '{feed} · desactualizado {age}s',
  'main.acars_label': 'acars',
  'main.acars_age_seconds': 'acars · {n}s',
  'main.acars_age_minutes': 'acars · {n}m',
  'main.acars_silent': 'acars sin actividad',
  'main.acars_down': 'acars caído',
  'main.share_copied': '¡copiado!',
  'main.loading_historical': 'Cargando histórico',
  'main.historical_loading': 'histórico · cargando…',
  'main.historical_counts': 'histórico · {visible}/{total}',
  'main.historical_error': 'histórico · error',
  'main.window_last_hour': 'última hora',
  'main.window_last_hours': 'últimas {n} horas',
  'main.window_last_days': 'últimos {n} días',
  'main.aircraft_count': 'aeronaves: {n}',
} as const;
