// Spanish draft mirroring en/misc.ts, pending native-speaker review.
export const miscStrings = {
  'misc.legend_tooltip':
    'Las aeronaves se colorean según la altitud (esquema tar1090): baja = naranja, ' +
    'media = verde, alta = magenta, +50k ft = rojo. Las aeronaves en tierra se ' +
    'muestran en gris tenue.\n\n' +
    'Nota: la vista 3D exagera la altitud {factor}× respecto a la distancia ' +
    'horizontal para que el tráfico sea legible; la altura que se ve NO está ' +
    'a escala con el suelo.',
  'misc.legend_alt_caption': 'alt',
  'misc.legend_scale_note': '↕ altura ×{factor}, no a escala',
  'misc.legend_scale_note_low': '↕ altitudes bajas enfatizadas, no a escala',
  'misc.legend_scale_note_high': '↕ altitudes altas enfatizadas, no a escala',
  // Menú de muñeca VR, deliberadamente corto: se dibuja en un canvas de 512px.
  'misc.xr_theme': 'Tema',
  'misc.xr_basemap': 'Mapa',
  'misc.xr_range_rings': 'Anillos',
  'misc.xr_labels': 'Etiquetas',
  'misc.xr_alt_lines': 'Líneas alt.',
  'misc.xr_on': 'sí',
  'misc.xr_off': 'no',
  'misc.xr_hint': 'apuntar + gatillo',
  'misc.xr_page': 'Página',
  'misc.xr_place': 'Colocar radar',
  'misc.xr_ground_icons': 'Iconos de suelo',
  'misc.xr_trails': 'Estelas',
  'misc.xr_diorama': 'Diorama',
  'misc.xr_diorama_size': 'Tamaño del diorama',
  'misc.xr_follow': 'Seguir',
  'misc.xr_shape': 'Forma de aeronave',
  'misc.xr_shape_cone': 'Cono',
  'misc.xr_shape_sphere': 'Esfera',
  'misc.xr_shape_silhouette': 'Silueta 3D',
  'misc.xr_acars': 'ACARS',
  'misc.xr_label_density': 'Densidad de etiquetas',
  'misc.xr_density_all': 'todas',
  'misc.xr_quality': 'Calidad',
  'misc.xr_q_low': 'baja',
  'misc.xr_q_balanced': 'equilibrada',
  'misc.xr_q_high': 'alta',
  'misc.xr_q_ultra': 'ultra',
  'misc.xr_alt_unit': 'Altitud',
  'misc.xr_speed_unit': 'Velocidad',
  'misc.xr_dist_unit': 'Distancia',
  'misc.exit_stereo': 'Salir del estéreo',
  'misc.xr_movement': 'Movimiento',
  'misc.xr_move_scope': 'radar',
  'misc.xr_move_freefly': 'vuelo libre',
  'misc.xr_turning': 'Giro',
  'misc.xr_turn_snap': 'pasos',
  'misc.xr_turn_smooth': 'continuo',
  'misc.xr_basemap_dark': 'Oscuro',
  'misc.xr_basemap_voyager': 'Voyager',
  'misc.xr_basemap_hillshade': 'Relieve',
  'misc.xr_basemap_topo': 'Topo',
  'misc.xr_basemap_satellite': 'Satélite',
  'misc.xr_basemap_osm': 'OSM',
  'misc.xr_basemap_sectional': 'FAA Seccional',
  'misc.xr_basemap_sectional_hybrid': 'Seccional + Vías',
  'misc.xr_basemap_helicopter': 'FAA Helicóptero',
  'misc.xr_basemap_ifr_low': 'IFR bajo',
  'misc.xr_basemap_ifr_high': 'IFR alto',
} as const;
