// Mirrors en/settings.ts — Spanish draft pending native-speaker review.
export const settingsStrings = {
  // Panel chrome
  'settings.title': 'Ajustes',
  'settings.close': 'Cerrar ajustes',

  // Theme section
  'settings.section_theme': 'Tema',
  'settings.color_theme': 'Tema de color',
  'settings.color_theme_desc': 'Paleta para paneles, acentos y el fondo de la escena. Auto sigue la preferencia claro/oscuro del sistema.',
  'settings.language': 'Idioma',
  'settings.language_desc': 'Idioma de la interfaz. Auto sigue la configuración regional del navegador. Cambiarlo recarga la página.',
  'settings.language_auto': 'Auto',

  // Display section
  'settings.section_display': 'Visualización',
  'settings.ground_sprites': 'Iconos de aeronave en tierra',
  'settings.ground_sprites_desc': 'Mostrar la silueta de tar1090 debajo de cada aeronave.',
  'settings.altitude_lines': 'Líneas de altitud',
  'settings.altitude_lines_desc': 'Línea vertical que une cada aeronave con su posición en tierra.',
  'settings.aircraft_labels': 'Etiquetas de aeronave',
  'settings.aircraft_labels_desc': 'Indicativo / matrícula / hex sobre cada aeronave.',
  'settings.acars_messages': 'Mensajes ACARS',
  'settings.acars_messages_desc': 'Mostrar mensajes de enlace de datos ACARS y el indicador de estado del receptor.',
  'settings.label_density': 'Densidad de etiquetas',
  'settings.label_density_desc': 'Valores más altos ocultan las etiquetas lejanas al acercar el zoom. 0 mantiene todas visibles.',
  'settings.label_density_all': 'todas',
  'settings.range_rings': 'Anillos de distancia',
  'settings.range_rings_desc': 'Anillos concéntricos de distancia cada 50 NM.',
  'settings.basemap': 'Mapa base',
  'settings.basemap_desc': 'Proveedor de teselas del mapa dibujado bajo la escena.',
  'settings.basemap_carto_dark': 'Carto Dark',
  'settings.basemap_carto_voyager': 'Carto Voyager (claro)',
  'settings.basemap_osm': 'OpenStreetMap',
  'settings.basemap_topo': 'OpenTopoMap',
  'settings.basemap_hillshade': 'ESRI Hillshade',
  'settings.basemap_satellite': 'ESRI Satélite',
  'settings.basemap_sectional': 'FAA Sectional (EE. UU.)',
  'settings.basemap_sectional_hybrid': 'FAA Sectional + carreteras (EE. UU.)',
  'settings.basemap_helicopter': 'FAA Helicopter (EE. UU.)',
  'settings.basemap_ifr_low': 'FAA IFR Low (EE. UU.)',
  'settings.basemap_ifr_high': 'FAA IFR High (EE. UU.)',

  // Stereo / VR section
  'settings.section_stereo_vr': 'Estéreo / RV',
  'settings.enter_vr': 'Entrar en RV',
  'settings.enter_vr_desc': 'Abrir una sesión WebXR inmersiva en un visor conectado (Meta Quest, Vision Pro, etc.).',
  'settings.exit_vr': 'Salir de RV',
  'settings.exit_vr_desc': 'Finalizar la sesión inmersiva activa.',
  'settings.exit_ar_first': 'Salga primero de la sesión de RA.',
  'settings.vr_unavailable': 'RV no disponible',
  'settings.webxr_unavailable': 'WebXR no está disponible en este navegador.',
  'settings.enter_ar': 'Entrar en RA',
  'settings.enter_ar_desc': 'Modo passthrough: aeronaves flotando en su habitación. Quest 3, Vision Pro.',
  'settings.exit_ar': 'Salir de RA',
  'settings.exit_ar_desc': 'Finalizar la sesión passthrough activa.',
  'settings.exit_vr_first': 'Salga primero de la sesión de RV.',
  'settings.ar_unavailable': 'RA no disponible',
  'settings.ar_unsupported': 'Este dispositivo no admite passthrough immersive-ar.',
  'settings.vr_quality': 'Calidad de renderizado RV',
  'settings.vr_quality_desc': 'Supermuestreo para RV inmersiva. Un valor más alto mantiene nítidas las aeronaves lejanas a costa de la GPU. Se aplica la próxima vez que entre en RV.',
  'settings.vr_quality_low': 'Baja (más rápida)',
  'settings.vr_quality_balanced': 'Equilibrada',
  'settings.vr_quality_high': 'Alta',
  'settings.vr_quality_ultra': 'Ultra (máxima nitidez)',
  'settings.stereo': 'Estéreo lado a lado',
  'settings.stereo_desc': 'Dividir la vista en mitades para ojo izquierdo/derecho, para Google Cardboard o un visor RV de teléfono. Se ignora mientras hay una sesión WebXR inmersiva activa.',
  'settings.stereo_strength': 'Intensidad del estéreo',
  'settings.stereo_strength_desc': 'Separación ocular con el estéreo activado. Un valor más alto da un 3D más profundo pero mayor fatiga visual.',

  // Units section
  'settings.section_units': 'Unidades',
  'settings.altitude_unit': 'Altitud',
  'settings.unit_feet': 'Pies (ft)',
  'settings.unit_meters': 'Metros (m)',
  'settings.speed_unit': 'Velocidad',
  'settings.unit_knots': 'Nudos (kt)',
  'settings.unit_mph': 'Millas/hora (mph)',
  'settings.unit_kmh': 'Kilómetros/hora (km/h)',
  'settings.distance_unit': 'Distancia',
  'settings.unit_nm': 'Millas náuticas (NM)',
  'settings.unit_km': 'Kilómetros (km)',

  // Range-row reset button
  'settings.reset_to_default': 'Restablecer al valor predeterminado ({value})',
  'settings.reset_row_to_default': 'Restablecer {label} al valor predeterminado',
  'settings.terrain_3d': 'Terreno 3D',
  'settings.terrain_3d_desc':
    'Eleva el mapa a la altitud real del terreno. Los anillos y marcadores ' +
    'siguen el terreno. Cambiarlo recarga la página.',
  'settings.altitude_curve': 'Escala de altitud',
  'settings.altitude_curve_desc':
    'Más bajo = enfoque en altitudes bajas, más alto = enfoque en altitudes ' +
    'altas. Cambiarlo recarga la página.',
  'settings.altitude_curve_fmt_linear': 'equilibrado',
  'settings.altitude_curve_fmt_low': 'baja {n}%',
  'settings.altitude_curve_fmt_high': 'alta {n}%',
} as const;
