// Spanish draft mirroring en/static.ts, pending native-speaker review.
export const staticStrings = {
  // HUD
  'static.live_feed_aria': 'Fuente de datos en vivo',
  // Time controls
  'static.time_mode_aria': 'Modo de tiempo',
  'static.mode_live': 'En vivo',
  'static.mode_historical': 'Histórico',
  'static.window_presets_aria': 'Ventanas predefinidas',
  'static.play_aria': 'Reproducir',
  'static.playback_cursor_aria': 'Cursor de reproducción',
  'static.playback_speed_aria': 'Velocidad de reproducción',
  'static.heatmap_toggle': 'mapa de calor',
  // Footer status bar
  'static.clocks_title': 'Local · UTC',
  'static.share': 'compartir',
  'static.share_title': 'Copiar un enlace para compartir',
  'static.recenter': 'centrar',
  'static.recenter_title': 'Centrar la vista en la ubicación base',
  'static.github_title': 'Código fuente en GitHub',
  'static.github_aria': 'Repositorio de GitHub',
  'static.coffee_title': 'Apoyar el desarrollo',
  'static.coffee_aria': 'Invítame a un café',
  // Aircraft list panel
  'static.toggle_aircraft_list_aria': 'Mostrar u ocultar la lista de aeronaves',
  'static.aircraft_list_aria': 'Lista de aeronaves',
  'static.aircraft_heading': 'Aeronaves',
  'static.list_search_placeholder': 'filtrar indicativo / matrícula / hex',
  'static.filter_by_status_aria': 'Filtrar por estado',
  'static.filter_all': 'Todos',
  'static.filter_air': 'Aire',
  'static.filter_ground': 'Tierra',
  'static.filter_mil': 'Mil',
  'static.filter_emerg': 'Emerg',
  'static.col_flight': 'Vuelo',
  'static.col_alt': 'Alt',
  'static.col_spd': 'Vel',
  'static.col_dist': 'Dist',
  // Aircraft detail panel
  'static.detail_share_aria': 'Copiar un enlace para compartir esta aeronave',
  'static.detail_share_title': 'Copiar enlace para compartir',
  'static.clear_selection_aria': 'Quitar selección',
  'static.airframe_heading': 'Célula',
  'static.detail_type': 'Tipo',
  'static.detail_reg': 'Matr.',
  'static.detail_alt': 'Alt',
  'static.detail_vert': 'Vert.',
  'static.detail_spd': 'Vel',
  'static.detail_hdg': 'Rbo',
  'static.detail_sqk': 'Sqk',
  'static.detail_pos': 'Pos',
  'static.detail_range': 'Dist.',
  'static.detail_seen': 'Visto',
  'static.autopilot_heading': 'Piloto automático',
  // ACARS browser
  'static.acars_browser_aria': 'Explorador de mensajes ACARS',
  'static.acars_messages_heading': 'Mensajes ACARS',
  'static.close_aria': 'Cerrar',
  'static.acars_search_placeholder': 'filtrar texto · vuelo · matrícula · etiqueta',
  'static.filter_by_label_aria': 'Filtrar por etiqueta',
} as const;
