// Spanish draft mirroring en/voice.ts — pending native-speaker review.
export const voiceStrings = {
  'voice.scanner_title': 'Escáner de voz',
  'voice.toggle_label': 'voz',
  'voice.no_activity': 'Sin actividad',
  'voice.channel_active': 'Canal activo',
  'voice.live_channel_activity': 'Actividad de canal en vivo',
  'voice.start_scanner': 'Iniciar escáner',
  'voice.pause_scanner': 'Pausar escáner',
  'voice.volume': 'Volumen',
  'voice.jump_to_live': '▼ {n} en cola — ir al directo',
  'voice.recent_calls': 'Llamadas recientes',
  'voice.playing_channel': 'Reproduciendo: {label}',
  'voice.time_now': 'ahora',
  'voice.time_seconds_ago': 'hace {n}s',
  'voice.time_minutes_ago': 'hace {n}m',
  'voice.time_hours_ago': 'hace {n}h',
  'voice.status_connecting': 'conectando…',
  'voice.status_ready': 'listo — presiona ▶ para iniciar el escáner',
  'voice.status_playing': 'reproduciendo · {label}',
  'voice.status_playing_scanner': 'reproduciendo · escáner',
  'voice.status_listening': 'escuchando — esperando actividad…',
  'voice.status_waiting': 'esperando actividad…',
  'voice.status_paused': 'en pausa',
  'voice.status_autoplay_blocked':
    'reproducción automática bloqueada — haz clic en ▶ para reanudar',
  'voice.status_play_failed': 'fallo de reproducción: {error}',
  'voice.status_clip_error': 'error de clip ({code}) — omitiendo',
  'voice.error_code': 'código {n}',
  'voice.error_unknown': 'desconocido',
  'voice.status_reconnecting': 'reconectando…',
} as const;
