// German draft mirroring en/detail.ts — pending native-speaker review.
export const detailStrings = {
  'detail.click_to_copy': 'Zum Kopieren klicken',
  'detail.route_source_acars': 'ACARS',
  'detail.route_source_acars_tooltip': 'Ziel aus ACARS-Datalink',
  'detail.eta': 'ETA {time}',
  'detail.phase_at_gate': 'Am Gate',
  'detail.phase_taxi_out': 'Rollt zum Start',
  'detail.phase_airborne': 'In der Luft',
  'detail.phase_taxi_in': 'Rollt zum Gate',
  'detail.phase_arrival_gate': 'Am Ankunftsgate',
  'detail.operator': 'Betreiber',
  'detail.class': 'Klasse',
  'detail.chip_military': 'Militär',
  'detail.chip_special_interest': 'Besonderes Interesse',
  'detail.chip_pia': 'PIA',
  'detail.chip_ladd': 'LADD',
  'detail.on_ground': 'GND',
  'detail.agl': '{agl} AGL',
  'detail.vertical_level': 'konstant',
  'detail.seconds_ago': 'vor {n}s',
  'detail.minutes_ago': 'vor {n}min',
  'detail.hours_ago': 'vor {n}h',
  'detail.selected_altitude': 'Gew. Höhe',
  'detail.fms_altitude': 'FMS-Höhe',
  'detail.selected_heading': 'Gew. Kurs',
  'detail.qnh': 'QNH',
  'detail.autopilot_modes': 'Modi',
  'detail.acars_err': 'Fehler {n}',
  'detail.acars_out': 'OUT {time}',
  'detail.acars_off': 'OFF {time}',
  'detail.acars_on': 'ON {time}',
  'detail.acars_in': 'IN {time}',
  'detail.acars_pos': 'Pos. {coords}',
  'detail.acars_no_text': '(kein Text)',
  'detail.category_light': 'Leicht (< 7t)',
  'detail.category_small': 'Klein (< 34t)',
  'detail.category_large': 'Groß (< 136t)',
  'detail.category_high_vortex': 'Groß mit starker Wirbelschleppe',
  'detail.category_heavy': 'Schwer (> 136t)',
  'detail.category_high_performance': 'Hochleistung',
  'detail.category_rotorcraft': 'Drehflügler',
  'detail.category_glider': 'Segelflugzeug',
  'detail.category_lighter_than_air': 'Leichter als Luft',
  'detail.category_parachutist': 'Fallschirmspringer',
  'detail.category_ultralight': 'Ultraleicht',
  'detail.category_uav': 'UAV',
  'detail.category_spacecraft': 'Raumfahrzeug',
  'detail.category_surface_unknown': 'Boden — unbekannt',
  'detail.category_surface_emergency': 'Boden — Einsatzfahrzeug',
  'detail.category_surface_service': 'Boden — Servicefahrzeug',
  'detail.category_surface_obstacle': 'Boden — festes Hindernis',
  'detail.compass_n': 'N',
  'detail.compass_ne': 'NO',
  'detail.compass_e': 'O',
  'detail.compass_se': 'SO',
  'detail.compass_s': 'S',
  'detail.compass_sw': 'SW',
  'detail.compass_w': 'W',
  'detail.compass_nw': 'NW',
} as const;
