// German counterpart of en/main.ts — draft translation pending native review.
export const mainStrings = {
  'main.status_live': 'live',
  'main.status_stale': 'veraltet',
  'main.status_down': 'offline',
  'main.status_connecting': 'verbinde',
  'main.status_historical': 'historisch',
  'main.connecting_feed': 'Verbinde',
  'main.feed_connecting': 'verbinde…',
  'main.feed_status_down': '{feed} · offline',
  'main.feed_status_stale': '{feed} · veraltet',
  'main.feed_status_stale_age': '{feed} · veraltet {age}s',
  'main.acars_label': 'acars',
  'main.acars_age_seconds': 'acars · {n}s',
  'main.acars_age_minutes': 'acars · {n}m',
  'main.acars_silent': 'acars still',
  'main.acars_down': 'acars offline',
  'main.share_copied': 'kopiert!',
  'main.loading_historical': 'Lade historische Daten',
  'main.historical_loading': 'historisch · lädt…',
  'main.historical_counts': 'historisch · {visible}/{total}',
  'main.historical_error': 'historisch · Fehler',
  'main.window_last_hour': 'letzte Stunde',
  'main.window_last_hours': 'letzte {n} Stunden',
  'main.window_last_days': 'letzte {n} Tage',
  'main.aircraft_count': 'Luftfahrzeuge: {n}',
} as const;
