// German draft mirroring en/misc.ts — pending native-speaker review.
export const miscStrings = {
  'misc.legend_tooltip':
    'Flugzeuge sind nach Höhe eingefärbt (tar1090-Schema): niedrig = Orange, ' +
    'mittel = Grün, hoch = Magenta, ab 50k ft = Rot. Flugzeuge am Boden sind ' +
    'gedämpft grau.\n\n' +
    'Hinweis: Die 3D-Ansicht überhöht die Höhe im Verhältnis zur horizontalen ' +
    'Entfernung um das {factor}-Fache, damit der Verkehr lesbar bleibt. ' +
    'Die dargestellte Höhe ist NICHT maßstabsgetreu zum Boden.',
  'misc.legend_alt_caption': 'Höhe',
  'misc.legend_scale_note': '↕ Höhe ×{factor}, nicht maßstabsgetreu',
  'misc.legend_scale_note_low': '↕ niedrige Höhen betont, nicht maßstabsgetreu',
  'misc.legend_scale_note_high': '↕ große Höhen betont, nicht maßstabsgetreu',
  // VR-Handgelenkmenü — bewusst kurz, wird auf eine 512px-Canvas gezeichnet.
  'misc.xr_theme': 'Design',
  'misc.xr_basemap': 'Karte',
  'misc.xr_range_rings': 'Ringe',
  'misc.xr_labels': 'Labels',
  'misc.xr_alt_lines': 'Höhenlinien',
  'misc.xr_on': 'an',
  'misc.xr_off': 'aus',
  'misc.xr_hint': 'Zeigen + Trigger',
  'misc.xr_page': 'Seite',
  'misc.xr_place': 'Scope platzieren',
  'misc.xr_ground_icons': 'Bodensymbole',
  'misc.xr_trails': 'Spuren',
  'misc.xr_diorama': 'Diorama',
  'misc.xr_diorama_size': 'Diorama-Größe',
  'misc.xr_follow': 'Folgen',
  'misc.xr_follow_random': 'Zufällig folgen',
  'misc.xr_auto_orbit': 'Auto-Umkreisung',
  'misc.xr_hi_res_tiles': 'Kacheln in HD',
  'misc.xr_shape': 'Flugzeugform',
  'misc.xr_shape_cone': 'Kegel',
  'misc.xr_shape_sphere': 'Kugel',
  'misc.xr_shape_silhouette': '3D-Silhouette',
  'misc.xr_acars': 'ACARS',
  'misc.xr_label_density': 'Label-Dichte',
  'misc.xr_density_all': 'alle',
  'misc.xr_quality': 'Qualität',
  'misc.xr_q_low': 'niedrig',
  'misc.xr_q_balanced': 'ausgewogen',
  'misc.xr_q_high': 'hoch',
  'misc.xr_q_ultra': 'ultra',
  'misc.xr_alt_unit': 'Höhe',
  'misc.xr_speed_unit': 'Geschw.',
  'misc.xr_dist_unit': 'Entfernung',
  'misc.exit_stereo': 'Stereo beenden',
  'misc.xr_movement': 'Bewegung',
  'misc.xr_move_scope': 'Scope',
  'misc.xr_move_freefly': 'Freiflug',
  'misc.xr_turning': 'Drehung',
  'misc.xr_turn_snap': 'Schritte',
  'misc.xr_turn_smooth': 'fließend',
  'misc.xr_basemap_dark': 'Dunkel',
  'misc.xr_basemap_voyager': 'Voyager',
  'misc.xr_basemap_hillshade': 'Relief',
  'misc.xr_basemap_topo': 'Topo',
  'misc.xr_basemap_satellite': 'Satellit',
  'misc.xr_basemap_osm': 'OSM',
  'misc.xr_basemap_sectional': 'FAA Sectional',
  'misc.xr_basemap_sectional_hybrid': 'Sectional + Straßen',
  'misc.xr_basemap_helicopter': 'FAA Helikopter',
  'misc.xr_basemap_ifr_low': 'IFR Low',
  'misc.xr_basemap_ifr_high': 'IFR High',
} as const;
