// German draft mirroring en/static.ts — pending native-speaker review.
export const staticStrings = {
  // HUD
  'static.live_feed_aria': 'Live-Datenfeed',
  // Time controls
  'static.time_mode_aria': 'Zeitmodus',
  'static.mode_live': 'Live',
  'static.mode_historical': 'Historisch',
  'static.window_presets_aria': 'Zeitfenster-Voreinstellungen',
  'static.play_aria': 'Abspielen',
  'static.playback_cursor_aria': 'Wiedergabeposition',
  'static.playback_speed_aria': 'Wiedergabegeschwindigkeit',
  'static.heatmap_toggle': 'Heatmap',
  // Footer status bar
  'static.clocks_title': 'Lokal · UTC',
  'static.share': 'teilen',
  'static.share_title': 'Teilbaren Link kopieren',
  'static.recenter': 'zentrieren',
  'static.orbit': 'umkreisen',
  'static.orbit_title': 'Langsam um das ausgewählte Flugzeug (oder die Radarmitte) kreisen',
  'static.recenter_title': 'Ansicht auf Heimposition zentrieren',
  'static.github_title': 'Quellcode auf GitHub',
  'static.github_aria': 'GitHub-Repository',
  'static.coffee_title': 'Entwicklung unterstützen',
  'static.coffee_aria': 'Spendier mir einen Kaffee',
  // Aircraft list panel
  'static.toggle_aircraft_list_aria': 'Flugzeugliste ein-/ausblenden',
  'static.aircraft_list_aria': 'Flugzeugliste',
  'static.aircraft_heading': 'Flugzeuge',
  'static.list_search_placeholder': 'Filter: Rufzeichen / Reg. / Hex',
  'static.list_search_clear_aria': 'Suchfilter löschen',
  'static.shape_chip_aria': 'Flugzeugform',
  'static.filter_by_status_aria': 'Nach Status filtern',
  'static.filter_all': 'Alle',
  'static.filter_air': 'Luft',
  'static.filter_ground': 'Boden',
  'static.filter_mil': 'Mil',
  'static.filter_emerg': 'Notfall',
  'static.col_flight': 'Flug',
  'static.col_alt': 'Höhe',
  'static.col_spd': 'Geschw.',
  'static.col_dist': 'Entf.',
  'static.list_minimize_aria': 'Flugzeugliste minimieren',
  'static.list_minimize_title': 'Minimieren',
  // Aircraft detail panel
  'static.detail_minimize_aria': 'Panel minimieren',
  'static.detail_minimize_title': 'Minimieren',
  'static.detail_restore_aria': 'Flugzeug-Panel wiederherstellen',
  'static.detail_share_aria': 'Teilbaren Link zu diesem Flugzeug kopieren',
  'static.detail_share_title': 'Share-Link kopieren',
  'static.clear_selection_aria': 'Auswahl aufheben',
  'static.airframe_heading': 'Zelle',
  'static.detail_type': 'Typ',
  'static.detail_reg': 'Reg.',
  'static.detail_alt': 'Höhe',
  'static.detail_vert': 'Vert.',
  'static.detail_spd': 'Geschw.',
  'static.detail_hdg': 'Kurs',
  'static.detail_sqk': 'Squawk',
  'static.detail_pos': 'Pos.',
  'static.detail_range': 'Entfernung',
  'static.detail_seen': 'Zuletzt',
  'static.autopilot_heading': 'Autopilot',
  // ACARS browser
  'static.acars_browser_aria': 'ACARS-Nachrichtenbrowser',
  'static.acars_messages_heading': 'ACARS-Nachrichten',
  'static.close_aria': 'Schließen',
  'static.acars_search_placeholder': 'Filter: Text · Flug · Reg. · Label',
  'static.filter_by_label_aria': 'Nach Label filtern',
} as const;
