// Mirrors en/voice.ts; German draft pending native-speaker review.
export const voiceStrings = {
  'voice.scanner_title': 'Sprachscanner',
  'voice.toggle_label': 'Funk',
  'voice.no_activity': 'Keine Aktivität',
  'voice.channel_active': 'Kanal aktiv',
  'voice.live_channel_activity': 'Live-Kanalaktivität',
  'voice.start_scanner': 'Scanner starten',
  'voice.pause_scanner': 'Scanner pausieren',
  'voice.volume': 'Lautstärke',
  'voice.jump_to_live': '▼ {n} in Warteschlange — zu Live springen',
  'voice.recent_calls': 'Letzte Funksprüche',
  'voice.playing_channel': 'Wiedergabe: {label}',
  'voice.time_now': 'jetzt',
  'voice.time_seconds_ago': 'vor {n}s',
  'voice.time_minutes_ago': 'vor {n}m',
  'voice.time_hours_ago': 'vor {n}h',
  'voice.status_connecting': 'verbinde…',
  'voice.status_ready': 'bereit — ▶ drücken, um Scanner zu starten',
  'voice.status_playing': 'Wiedergabe · {label}',
  'voice.status_playing_scanner': 'Wiedergabe · Scanner',
  'voice.status_listening': 'empfangsbereit — warte auf Aktivität…',
  'voice.status_waiting': 'warte auf Aktivität…',
  'voice.status_paused': 'pausiert',
  'voice.status_autoplay_blocked': 'Autoplay blockiert — ▶ klicken zum Fortsetzen',
  'voice.status_play_failed': 'Wiedergabe fehlgeschlagen: {error}',
  'voice.status_clip_error': 'Clip-Fehler ({code}) — wird übersprungen',
  'voice.error_code': 'Code {n}',
  'voice.error_unknown': 'unbekannt',
  'voice.status_reconnecting': 'verbinde neu…',
} as const;
