name: Docker Build and Publish

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test health endpoint
        if: github.event_name != 'pull_request'
        run: |
          echo "Waiting for container to start..."
          sleep 10
          docker run --rm -d --name test-adsb-3d \
            -e LATITUDE=45.0000 \
            -e LONGITUDE=-90.0000 \
            -e ALTITUDE=1234 \
            -e FEEDER_HOST=localhost \
            -p 8086:80 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

          sleep 5

          # Test health endpoint
          HEALTH=$(curl -s http://localhost:8086/health)
          if [ "$HEALTH" != "OK" ]; then
            echo "Health check failed!"
            docker logs test-adsb-3d
            exit 1
          fi

          echo "Health check passed!"
          docker stop test-adsb-3d
